### ISSUE TITLE
Can't display the widget on jupyterlab

### ISSUE THREAD

**Issue by superjcd** [tridentbio/trident-chemwidgets#13]
After installing tht extention, and followed the code example listed on the README , I got the following err at Jupyterlab:
 
![image](https://user-images.githubusercontent.com/25010312/175481038-99a8d683-952f-4f71-a718-9ab2dc124bf1.png)

### Some error infomation reported by the browser

![image](https://user-images.githubusercontent.com/25010312/175481309-c4666945-ab67-4bdf-9a77-bc130b99a45e.png)

**Comment by TShimko126** [comment]
@superjcd - Thanks for raising this issue. It should be fixed in https://github.com/tridentbio/trident-chemwidgets/pull/14, which we'll be building and pushing to PyPI later today. I'll update here when it's ready.

**Comment by superjcd** [comment]
收到了，谢谢

**Comment by TShimko126** [comment]
We just published [v0.2.1 to PyPI](https://pypi.org/project/trident-chemwidgets/0.2.1/#history), so this issue should be fixed in the pip installable version. Closing this issue for now, but feel free to reopen if it persists. Thanks again for your report!
